filepath: ""
helmfiles:
- path: helmfiles/examplejenkins/helmfile.yaml
- path: helmfiles/jx/helmfile.yaml
- path: helmfiles/secret-infra/helmfile.yaml
- path: helmfiles/tekton-pipelines/helmfile.yaml
templates: {}
renderedvalues: {}
