apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jenkins-x-sampleproject
    provider: github
    repository: nodehttp
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: jenkins-x-sampleproject-nodehttp
  namespace: jx
spec:
  httpCloneURL: https://github.com/jenkins-x-sampleproject/nodehttp.git
  org: jenkins-x-sampleproject
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: nodehttp
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/jenkins-x-sampleproject/nodehttp
