# Source: jenkins/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins
  namespace: jenkinxnew
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-4.5.0"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"jenkins","properties":[{"name":"jenkins-admin-user","question":"the pipeline username","help":"the user to login to Jenkins","defaultValue":"admin"},{"name":"jenkins-admin-password","question":"the pipeline token or password","help":"the password to login to Jenkins","generator":"password"}],"mandatory":true}'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
  - name: jenkins-admin-password
    key: secret/data/jenkins
    property: jenkins-admin-password
  - name: jenkins-admin-user
    key: secret/data/jenkins
    property: jenkins-admin-user
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'jenkins'
        secret.jenkins-x.io/schema-object: '{"name":"jenkins","properties":[{"name":"jenkins-admin-user","question":"the pipeline username","help":"the user to login to Jenkins","defaultValue":"admin"},{"name":"jenkins-admin-password","question":"the pipeline token or password","help":"the password to login to Jenkins","generator":"password"}],"mandatory":true}'
      labels:
        "app.kubernetes.io/name": 'jenkins'
        "helm.sh/chart": "jenkins-4.5.0"
        "app.kubernetes.io/managed-by": "Helm"
        "app.kubernetes.io/instance": "jenkins"
        "app.kubernetes.io/component": "jenkins-controller"
    type: Opaque
